//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERPExportSales.Web.ExportSalesWebService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ExportSalesWebService.SFCServiceSoap")]
    public interface SFCServiceSoap {
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 用户 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/记日志", ReplyAction="*")]
        ERPExportSales.Web.ExportSalesWebService.记日志Response 记日志(ERPExportSales.Web.ExportSalesWebService.记日志Request request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/记日志", ReplyAction="*")]
        System.Threading.Tasks.Task<ERPExportSales.Web.ExportSalesWebService.记日志Response> 记日志Async(ERPExportSales.Web.ExportSalesWebService.记日志Request request);
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 大类 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/获取更新文件大小", ReplyAction="*")]
        ERPExportSales.Web.ExportSalesWebService.获取更新文件大小Response 获取更新文件大小(ERPExportSales.Web.ExportSalesWebService.获取更新文件大小Request request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/获取更新文件大小", ReplyAction="*")]
        System.Threading.Tasks.Task<ERPExportSales.Web.ExportSalesWebService.获取更新文件大小Response> 获取更新文件大小Async(ERPExportSales.Web.ExportSalesWebService.获取更新文件大小Request request);
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 文件 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/上传更新文件", ReplyAction="*")]
        ERPExportSales.Web.ExportSalesWebService.上传更新文件Response 上传更新文件(ERPExportSales.Web.ExportSalesWebService.上传更新文件Request request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/上传更新文件", ReplyAction="*")]
        System.Threading.Tasks.Task<ERPExportSales.Web.ExportSalesWebService.上传更新文件Response> 上传更新文件Async(ERPExportSales.Web.ExportSalesWebService.上传更新文件Request request);
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 大类 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/删除更新文件", ReplyAction="*")]
        ERPExportSales.Web.ExportSalesWebService.删除更新文件Response 删除更新文件(ERPExportSales.Web.ExportSalesWebService.删除更新文件Request request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/删除更新文件", ReplyAction="*")]
        System.Threading.Tasks.Task<ERPExportSales.Web.ExportSalesWebService.删除更新文件Response> 删除更新文件Async(ERPExportSales.Web.ExportSalesWebService.删除更新文件Request request);
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 客户端IP 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/下载附件", ReplyAction="*")]
        ERPExportSales.Web.ExportSalesWebService.下载附件Response 下载附件(ERPExportSales.Web.ExportSalesWebService.下载附件Request request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/下载附件", ReplyAction="*")]
        System.Threading.Tasks.Task<ERPExportSales.Web.ExportSalesWebService.下载附件Response> 下载附件Async(ERPExportSales.Web.ExportSalesWebService.下载附件Request request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class 记日志Request {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="记日志", Namespace="http://tempuri.org/", Order=0)]
        public ERPExportSales.Web.ExportSalesWebService.记日志RequestBody Body;
        
        public 记日志Request() {
        }
        
        public 记日志Request(ERPExportSales.Web.ExportSalesWebService.记日志RequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class 记日志RequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string 用户;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string 日志标题;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string 日志;
        
        public 记日志RequestBody() {
        }
        
        public 记日志RequestBody(string 用户, string 日志标题, string 日志) {
            this.用户 = 用户;
            this.日志标题 = 日志标题;
            this.日志 = 日志;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class 记日志Response {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="记日志Response", Namespace="http://tempuri.org/", Order=0)]
        public ERPExportSales.Web.ExportSalesWebService.记日志ResponseBody Body;
        
        public 记日志Response() {
        }
        
        public 记日志Response(ERPExportSales.Web.ExportSalesWebService.记日志ResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class 记日志ResponseBody {
        
        public 记日志ResponseBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class 获取更新文件大小Request {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="获取更新文件大小", Namespace="http://tempuri.org/", Order=0)]
        public ERPExportSales.Web.ExportSalesWebService.获取更新文件大小RequestBody Body;
        
        public 获取更新文件大小Request() {
        }
        
        public 获取更新文件大小Request(ERPExportSales.Web.ExportSalesWebService.获取更新文件大小RequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class 获取更新文件大小RequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string 大类;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string 标准系列;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string 文件名;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string 三级目录;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string 四级目录;
        
        public 获取更新文件大小RequestBody() {
        }
        
        public 获取更新文件大小RequestBody(string 大类, string 标准系列, string 文件名, string 三级目录, string 四级目录) {
            this.大类 = 大类;
            this.标准系列 = 标准系列;
            this.文件名 = 文件名;
            this.三级目录 = 三级目录;
            this.四级目录 = 四级目录;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class 获取更新文件大小Response {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="获取更新文件大小Response", Namespace="http://tempuri.org/", Order=0)]
        public ERPExportSales.Web.ExportSalesWebService.获取更新文件大小ResponseBody Body;
        
        public 获取更新文件大小Response() {
        }
        
        public 获取更新文件大小Response(ERPExportSales.Web.ExportSalesWebService.获取更新文件大小ResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class 获取更新文件大小ResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public long 获取更新文件大小Result;
        
        public 获取更新文件大小ResponseBody() {
        }
        
        public 获取更新文件大小ResponseBody(long 获取更新文件大小Result) {
            this.获取更新文件大小Result = 获取更新文件大小Result;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class 上传更新文件Request {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="上传更新文件", Namespace="http://tempuri.org/", Order=0)]
        public ERPExportSales.Web.ExportSalesWebService.上传更新文件RequestBody Body;
        
        public 上传更新文件Request() {
        }
        
        public 上传更新文件Request(ERPExportSales.Web.ExportSalesWebService.上传更新文件RequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class 上传更新文件RequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public byte[] 文件;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string 大类;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string 标准系列;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string 文件名;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string 三级目录;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string 四级目录;
        
        public 上传更新文件RequestBody() {
        }
        
        public 上传更新文件RequestBody(byte[] 文件, string 大类, string 标准系列, string 文件名, string 三级目录, string 四级目录) {
            this.文件 = 文件;
            this.大类 = 大类;
            this.标准系列 = 标准系列;
            this.文件名 = 文件名;
            this.三级目录 = 三级目录;
            this.四级目录 = 四级目录;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class 上传更新文件Response {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="上传更新文件Response", Namespace="http://tempuri.org/", Order=0)]
        public ERPExportSales.Web.ExportSalesWebService.上传更新文件ResponseBody Body;
        
        public 上传更新文件Response() {
        }
        
        public 上传更新文件Response(ERPExportSales.Web.ExportSalesWebService.上传更新文件ResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class 上传更新文件ResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool 上传更新文件Result;
        
        public 上传更新文件ResponseBody() {
        }
        
        public 上传更新文件ResponseBody(bool 上传更新文件Result) {
            this.上传更新文件Result = 上传更新文件Result;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class 删除更新文件Request {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="删除更新文件", Namespace="http://tempuri.org/", Order=0)]
        public ERPExportSales.Web.ExportSalesWebService.删除更新文件RequestBody Body;
        
        public 删除更新文件Request() {
        }
        
        public 删除更新文件Request(ERPExportSales.Web.ExportSalesWebService.删除更新文件RequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class 删除更新文件RequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string 大类;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string 标准系列;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string 文件名;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string 三级目录;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string 四级目录;
        
        public 删除更新文件RequestBody() {
        }
        
        public 删除更新文件RequestBody(string 大类, string 标准系列, string 文件名, string 三级目录, string 四级目录) {
            this.大类 = 大类;
            this.标准系列 = 标准系列;
            this.文件名 = 文件名;
            this.三级目录 = 三级目录;
            this.四级目录 = 四级目录;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class 删除更新文件Response {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="删除更新文件Response", Namespace="http://tempuri.org/", Order=0)]
        public ERPExportSales.Web.ExportSalesWebService.删除更新文件ResponseBody Body;
        
        public 删除更新文件Response() {
        }
        
        public 删除更新文件Response(ERPExportSales.Web.ExportSalesWebService.删除更新文件ResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class 删除更新文件ResponseBody {
        
        public 删除更新文件ResponseBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class 下载附件Request {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="下载附件", Namespace="http://tempuri.org/", Order=0)]
        public ERPExportSales.Web.ExportSalesWebService.下载附件RequestBody Body;
        
        public 下载附件Request() {
        }
        
        public 下载附件Request(ERPExportSales.Web.ExportSalesWebService.下载附件RequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class 下载附件RequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string 客户端IP;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string 大类;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string 标准系列;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string 文件名;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string 三级目录;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string 四级目录;
        
        public 下载附件RequestBody() {
        }
        
        public 下载附件RequestBody(string 客户端IP, string 大类, string 标准系列, string 文件名, string 三级目录, string 四级目录) {
            this.客户端IP = 客户端IP;
            this.大类 = 大类;
            this.标准系列 = 标准系列;
            this.文件名 = 文件名;
            this.三级目录 = 三级目录;
            this.四级目录 = 四级目录;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class 下载附件Response {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="下载附件Response", Namespace="http://tempuri.org/", Order=0)]
        public ERPExportSales.Web.ExportSalesWebService.下载附件ResponseBody Body;
        
        public 下载附件Response() {
        }
        
        public 下载附件Response(ERPExportSales.Web.ExportSalesWebService.下载附件ResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class 下载附件ResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public byte[] 下载附件Result;
        
        public 下载附件ResponseBody() {
        }
        
        public 下载附件ResponseBody(byte[] 下载附件Result) {
            this.下载附件Result = 下载附件Result;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface SFCServiceSoapChannel : ERPExportSales.Web.ExportSalesWebService.SFCServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SFCServiceSoapClient : System.ServiceModel.ClientBase<ERPExportSales.Web.ExportSalesWebService.SFCServiceSoap>, ERPExportSales.Web.ExportSalesWebService.SFCServiceSoap {
        
        public SFCServiceSoapClient() {
        }
        
        public SFCServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SFCServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SFCServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SFCServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ERPExportSales.Web.ExportSalesWebService.记日志Response ERPExportSales.Web.ExportSalesWebService.SFCServiceSoap.记日志(ERPExportSales.Web.ExportSalesWebService.记日志Request request) {
            return base.Channel.记日志(request);
        }
        
        public void 记日志(string 用户, string 日志标题, string 日志) {
            ERPExportSales.Web.ExportSalesWebService.记日志Request inValue = new ERPExportSales.Web.ExportSalesWebService.记日志Request();
            inValue.Body = new ERPExportSales.Web.ExportSalesWebService.记日志RequestBody();
            inValue.Body.用户 = 用户;
            inValue.Body.日志标题 = 日志标题;
            inValue.Body.日志 = 日志;
            ERPExportSales.Web.ExportSalesWebService.记日志Response retVal = ((ERPExportSales.Web.ExportSalesWebService.SFCServiceSoap)(this)).记日志(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ERPExportSales.Web.ExportSalesWebService.记日志Response> ERPExportSales.Web.ExportSalesWebService.SFCServiceSoap.记日志Async(ERPExportSales.Web.ExportSalesWebService.记日志Request request) {
            return base.Channel.记日志Async(request);
        }
        
        public System.Threading.Tasks.Task<ERPExportSales.Web.ExportSalesWebService.记日志Response> 记日志Async(string 用户, string 日志标题, string 日志) {
            ERPExportSales.Web.ExportSalesWebService.记日志Request inValue = new ERPExportSales.Web.ExportSalesWebService.记日志Request();
            inValue.Body = new ERPExportSales.Web.ExportSalesWebService.记日志RequestBody();
            inValue.Body.用户 = 用户;
            inValue.Body.日志标题 = 日志标题;
            inValue.Body.日志 = 日志;
            return ((ERPExportSales.Web.ExportSalesWebService.SFCServiceSoap)(this)).记日志Async(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ERPExportSales.Web.ExportSalesWebService.获取更新文件大小Response ERPExportSales.Web.ExportSalesWebService.SFCServiceSoap.获取更新文件大小(ERPExportSales.Web.ExportSalesWebService.获取更新文件大小Request request) {
            return base.Channel.获取更新文件大小(request);
        }
        
        public long 获取更新文件大小(string 大类, string 标准系列, string 文件名, string 三级目录, string 四级目录) {
            ERPExportSales.Web.ExportSalesWebService.获取更新文件大小Request inValue = new ERPExportSales.Web.ExportSalesWebService.获取更新文件大小Request();
            inValue.Body = new ERPExportSales.Web.ExportSalesWebService.获取更新文件大小RequestBody();
            inValue.Body.大类 = 大类;
            inValue.Body.标准系列 = 标准系列;
            inValue.Body.文件名 = 文件名;
            inValue.Body.三级目录 = 三级目录;
            inValue.Body.四级目录 = 四级目录;
            ERPExportSales.Web.ExportSalesWebService.获取更新文件大小Response retVal = ((ERPExportSales.Web.ExportSalesWebService.SFCServiceSoap)(this)).获取更新文件大小(inValue);
            return retVal.Body.获取更新文件大小Result;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ERPExportSales.Web.ExportSalesWebService.获取更新文件大小Response> ERPExportSales.Web.ExportSalesWebService.SFCServiceSoap.获取更新文件大小Async(ERPExportSales.Web.ExportSalesWebService.获取更新文件大小Request request) {
            return base.Channel.获取更新文件大小Async(request);
        }
        
        public System.Threading.Tasks.Task<ERPExportSales.Web.ExportSalesWebService.获取更新文件大小Response> 获取更新文件大小Async(string 大类, string 标准系列, string 文件名, string 三级目录, string 四级目录) {
            ERPExportSales.Web.ExportSalesWebService.获取更新文件大小Request inValue = new ERPExportSales.Web.ExportSalesWebService.获取更新文件大小Request();
            inValue.Body = new ERPExportSales.Web.ExportSalesWebService.获取更新文件大小RequestBody();
            inValue.Body.大类 = 大类;
            inValue.Body.标准系列 = 标准系列;
            inValue.Body.文件名 = 文件名;
            inValue.Body.三级目录 = 三级目录;
            inValue.Body.四级目录 = 四级目录;
            return ((ERPExportSales.Web.ExportSalesWebService.SFCServiceSoap)(this)).获取更新文件大小Async(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ERPExportSales.Web.ExportSalesWebService.上传更新文件Response ERPExportSales.Web.ExportSalesWebService.SFCServiceSoap.上传更新文件(ERPExportSales.Web.ExportSalesWebService.上传更新文件Request request) {
            return base.Channel.上传更新文件(request);
        }
        
        public bool 上传更新文件(byte[] 文件, string 大类, string 标准系列, string 文件名, string 三级目录, string 四级目录) {
            ERPExportSales.Web.ExportSalesWebService.上传更新文件Request inValue = new ERPExportSales.Web.ExportSalesWebService.上传更新文件Request();
            inValue.Body = new ERPExportSales.Web.ExportSalesWebService.上传更新文件RequestBody();
            inValue.Body.文件 = 文件;
            inValue.Body.大类 = 大类;
            inValue.Body.标准系列 = 标准系列;
            inValue.Body.文件名 = 文件名;
            inValue.Body.三级目录 = 三级目录;
            inValue.Body.四级目录 = 四级目录;
            ERPExportSales.Web.ExportSalesWebService.上传更新文件Response retVal = ((ERPExportSales.Web.ExportSalesWebService.SFCServiceSoap)(this)).上传更新文件(inValue);
            return retVal.Body.上传更新文件Result;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ERPExportSales.Web.ExportSalesWebService.上传更新文件Response> ERPExportSales.Web.ExportSalesWebService.SFCServiceSoap.上传更新文件Async(ERPExportSales.Web.ExportSalesWebService.上传更新文件Request request) {
            return base.Channel.上传更新文件Async(request);
        }
        
        public System.Threading.Tasks.Task<ERPExportSales.Web.ExportSalesWebService.上传更新文件Response> 上传更新文件Async(byte[] 文件, string 大类, string 标准系列, string 文件名, string 三级目录, string 四级目录) {
            ERPExportSales.Web.ExportSalesWebService.上传更新文件Request inValue = new ERPExportSales.Web.ExportSalesWebService.上传更新文件Request();
            inValue.Body = new ERPExportSales.Web.ExportSalesWebService.上传更新文件RequestBody();
            inValue.Body.文件 = 文件;
            inValue.Body.大类 = 大类;
            inValue.Body.标准系列 = 标准系列;
            inValue.Body.文件名 = 文件名;
            inValue.Body.三级目录 = 三级目录;
            inValue.Body.四级目录 = 四级目录;
            return ((ERPExportSales.Web.ExportSalesWebService.SFCServiceSoap)(this)).上传更新文件Async(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ERPExportSales.Web.ExportSalesWebService.删除更新文件Response ERPExportSales.Web.ExportSalesWebService.SFCServiceSoap.删除更新文件(ERPExportSales.Web.ExportSalesWebService.删除更新文件Request request) {
            return base.Channel.删除更新文件(request);
        }
        
        public void 删除更新文件(string 大类, string 标准系列, string 文件名, string 三级目录, string 四级目录) {
            ERPExportSales.Web.ExportSalesWebService.删除更新文件Request inValue = new ERPExportSales.Web.ExportSalesWebService.删除更新文件Request();
            inValue.Body = new ERPExportSales.Web.ExportSalesWebService.删除更新文件RequestBody();
            inValue.Body.大类 = 大类;
            inValue.Body.标准系列 = 标准系列;
            inValue.Body.文件名 = 文件名;
            inValue.Body.三级目录 = 三级目录;
            inValue.Body.四级目录 = 四级目录;
            ERPExportSales.Web.ExportSalesWebService.删除更新文件Response retVal = ((ERPExportSales.Web.ExportSalesWebService.SFCServiceSoap)(this)).删除更新文件(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ERPExportSales.Web.ExportSalesWebService.删除更新文件Response> ERPExportSales.Web.ExportSalesWebService.SFCServiceSoap.删除更新文件Async(ERPExportSales.Web.ExportSalesWebService.删除更新文件Request request) {
            return base.Channel.删除更新文件Async(request);
        }
        
        public System.Threading.Tasks.Task<ERPExportSales.Web.ExportSalesWebService.删除更新文件Response> 删除更新文件Async(string 大类, string 标准系列, string 文件名, string 三级目录, string 四级目录) {
            ERPExportSales.Web.ExportSalesWebService.删除更新文件Request inValue = new ERPExportSales.Web.ExportSalesWebService.删除更新文件Request();
            inValue.Body = new ERPExportSales.Web.ExportSalesWebService.删除更新文件RequestBody();
            inValue.Body.大类 = 大类;
            inValue.Body.标准系列 = 标准系列;
            inValue.Body.文件名 = 文件名;
            inValue.Body.三级目录 = 三级目录;
            inValue.Body.四级目录 = 四级目录;
            return ((ERPExportSales.Web.ExportSalesWebService.SFCServiceSoap)(this)).删除更新文件Async(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ERPExportSales.Web.ExportSalesWebService.下载附件Response ERPExportSales.Web.ExportSalesWebService.SFCServiceSoap.下载附件(ERPExportSales.Web.ExportSalesWebService.下载附件Request request) {
            return base.Channel.下载附件(request);
        }
        
        public byte[] 下载附件(string 客户端IP, string 大类, string 标准系列, string 文件名, string 三级目录, string 四级目录) {
            ERPExportSales.Web.ExportSalesWebService.下载附件Request inValue = new ERPExportSales.Web.ExportSalesWebService.下载附件Request();
            inValue.Body = new ERPExportSales.Web.ExportSalesWebService.下载附件RequestBody();
            inValue.Body.客户端IP = 客户端IP;
            inValue.Body.大类 = 大类;
            inValue.Body.标准系列 = 标准系列;
            inValue.Body.文件名 = 文件名;
            inValue.Body.三级目录 = 三级目录;
            inValue.Body.四级目录 = 四级目录;
            ERPExportSales.Web.ExportSalesWebService.下载附件Response retVal = ((ERPExportSales.Web.ExportSalesWebService.SFCServiceSoap)(this)).下载附件(inValue);
            return retVal.Body.下载附件Result;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ERPExportSales.Web.ExportSalesWebService.下载附件Response> ERPExportSales.Web.ExportSalesWebService.SFCServiceSoap.下载附件Async(ERPExportSales.Web.ExportSalesWebService.下载附件Request request) {
            return base.Channel.下载附件Async(request);
        }
        
        public System.Threading.Tasks.Task<ERPExportSales.Web.ExportSalesWebService.下载附件Response> 下载附件Async(string 客户端IP, string 大类, string 标准系列, string 文件名, string 三级目录, string 四级目录) {
            ERPExportSales.Web.ExportSalesWebService.下载附件Request inValue = new ERPExportSales.Web.ExportSalesWebService.下载附件Request();
            inValue.Body = new ERPExportSales.Web.ExportSalesWebService.下载附件RequestBody();
            inValue.Body.客户端IP = 客户端IP;
            inValue.Body.大类 = 大类;
            inValue.Body.标准系列 = 标准系列;
            inValue.Body.文件名 = 文件名;
            inValue.Body.三级目录 = 三级目录;
            inValue.Body.四级目录 = 四级目录;
            return ((ERPExportSales.Web.ExportSalesWebService.SFCServiceSoap)(this)).下载附件Async(inValue);
        }
    }
}
